### ISSUE TITLE
[FEAT] 서버 통신 기초 세팅

### ISSUE THREAD

**Issue by heerucan** [HowIsTheMootherToday/Moother_KimRuHee#13]
## 💡 Issue
서버 통신을 위한 기초 세팅을 해주자!

## 📝  todo
- [x] 어떤 API를 사용할 지 결정
- [x] API Service 파일 생성
- [x] info.plist - moya 사용을 위해 세팅
