### ISSUE TITLE
[FEAT] Main View 서버 연결

### ISSUE THREAD

**Issue by heerucan** [HowIsTheMootherToday/Moother_KimRuHee#16]
## 💡 Issue
Main View 서버 연결해보려고 합니다.

## 📝  todo
- [x] 상단 데이터 연결
- [x] 시간별TVC 데이터 연결
- [x] 데일리TVC 데이터 연결
- [x] 투데이TVC 데이터 연결
- [x] 디테일TVC 데이터 연결
- [x] 멥TVC 데이터 연결
