### ISSUE TITLE
[FEAT] 시간과 날씨에 따라서 배경색상 및 Lottie 설정

### ISSUE THREAD

**Issue by heerucan** [HowIsTheMootherToday/Moother_KimRuHee#20]
## 💡 Issue
시간이랑 날씨에 따라 밤낮 색상 그리고 Lottie 설정

## 📝  todo
- [x] background Color 시간에 따라 분기처리 해주기
- [x] 필요한 Lottie 추가
- [x] 날씨 분기처리해서 Lottie 적용
- [x] background 갔다와도 재생하시키기
