### ISSUE TITLE
[FEAT] Main View Animation

### ISSUE THREAD

**Issue by heerucan** [HowIsTheMootherToday/Moother_KimRuHee#5]
## 💡 Issue
Main View 상단 애니메이션을 구현합니다.

## 📝  todo
- [x] UIView 스크롤 되게 해주기
- [x] alpha 값 조정해서 사라지게 하기
- [x] 상단 topLocalView height 고정해주기
